name: Run Tests

on:
  pull_request_review:
    types: [submitted]
  push:
    branches:
      - main

jobs:
  test:
    name: Test on Python 3.11
    runs-on: ubuntu-latest
    if: ((github.event_name == 'pull_request_review' && github.event.review.state == 'approved') || github.event_name == 'push')

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user pipenv
          pipenv install
          pipenv run python -m pip install pytest

      - name: Run tests
        run: |
          cd machine-learning-client
          pipenv run coverage run -m pytest
          pipenv run coverage report --include=src/**/*.py --fail-under=80
#          cd ..
#          cd web-app
#          pipenv run coverage run -m pytest
#          pipenv run coverage report --include=src/**/*.py --fail-under=80